class HomePage:
    A_DATA_INSIGHTS = '(//a[normalize-space() = "Data Insights"])[2]'
    Eligibility_Batch_Review = 'a:has-text("Eligibility Batch Review")'
    IFRAME_MSG_BATCH = '#ctl00_ContentPlaceHolder1_divEligibilityBatchReview'
    Eligibility_Batch_Review_Search = '#ctl00_ContentPlaceHolder1_btnSearch'
    Monitor_Process = 'text="HHAeXchange - Process Monitor"'
    A_EVV_Aggregator = '(//a[normalize-space() = "EVV Aggregation Transaction Manager"])[2]'
    A_CUSTOM_EXPORT = '(//a[contains(text(), "Custom Export")])[2]'
    A_SYSTEM_NOTIFICATIONS = '//*[@id="sysNoti-label"]'
    A_SELECT_PRIORITY = "//select[@id='ddlPrioritySent']/option[2]"
    A_PRIORITY_DROPDOWN = "#ddlPrioritySent"
    A_SYSTEM_NOTIFICATION_TEXT = '//h2[text()="Search System Notifications"]'
    A_NEW_PAYROLL = 'a:has-text("New Payroll")'
    A_PAYROLL = 'a:has-text("Payroll")'
    A_SEARCH_BY_BATCH = 'a:has-text("Search By Batch")'
    DIV_SPINNER = '#load-spinner-main'
    A_Compliance_Setup = 'a:has-text("Compliance Setup")'
    A_Item_Manager = '(//a[normalize-space() = "Item Manager"])[2]'
    A_Search_Setup = 'a:has-text("Search Setups")'
    HOME = 'a:has-text("Home")'
    A_ADMIN = 'a:has-text("Admin")'
    A_MANAGE_REPORT = 'a:has-text("Manage Report Subscription")'
    A_FAMILY_PORTAL_GLOBAL_MGNT = "//*[@id='ulMenu']//a[contains(text(),'Family Portal Global Management')]"
    A_REGISTERED_FAMILY_MEMBER = "//*[@id='ulMenu']//a[contains(text(),'Registered Family Members')]"
    A_CONTRACT_SETUP = 'a:has-text("Contract Setup")'
    A_NEW_CONTRACT = 'a:has-text("New Contract")'
    A_SEARCH_CONTRACT = 'a:has-text("Search Contract")'
    A_OFFICE_SETUP = 'a:has-text("Office Setup")'
    A_NEW_OFFICE = 'a:has-text("New Office")'
    A_SEARCH_OFFICE = 'a:has-text("Search Office")'
    A_PATIENT = 'a:has-text("Patient")'
    A_PROVIDER_AND_CAREGIVER = 'a:has-text("Provider and Caregiver")'
    A_HOME = 'a:has-text("Home")'
    A_NEW_PATIENT = 'a:has-text("New Patient")'
    A_SEARCH_PATIENT = 'a:has-text("Search Patient")'
    A_CAREGIVER = 'a:has-text("Caregiver")'
    A_TRAINEE = 'a:has-text("Trainee")'
    A_NEW_TRAINEE = 'a:has-text("New Trainee")'
    A_SEARCH_TRAINEE = 'a:has-text("Search Trainee")'
    A_NEW_CAREGIVER = 'a:has-text("New Caregiver")'
    A_SEARCH_CAREGIVER = 'a:has-text("Search Caregiver")'
    A_New_SEARCH_CAREGIVER = 'a:has-text("Search Caregiver")'
    A_New_SEARCH_CAREGIVER_Under_Search = "(//a[text()='Search Caregiver'])[2]"
    A_ORG_STRUCTURE = 'a:has-text("Org. Structure")'
    A_ORDER_TRACKING = 'a:has-text("Order Tracking")'
    A_BILLING = 'a:has-text("Billing")'
    A_BILLING_REVIEW = 'a:has-text("Billing Review")'
    A_NEW_INVOICE_INTERNAL = 'a:has-text("New Invoice - (Internal")'
    A_NEW_INVOICE_BATCH = 'a:has-text("New Invoice Batch")'
    A_PROCESS_MONITOR = 'a:has-text("Process Monitor")'
    A_CASH_PAYMENT = 'a:has-text("Cash Payment")'
    A_SUPPORT_MENU = 'a:has-text("Support Menu")'
    A_SUPPORT_MENU_PAYER = 'a:has-text("Support Menu Payer")'
    A_LOGOUT = 'a:has-text("Logout")'
    A_PAYER_PROFILE_MENU = 'a:has-text("Payer Profile Menu")'
    A_INVOICE_SEARCH = 'a:has-text("Invoice Search")'
    A_BY_BATCH = 'a:has-text("By Batch")'
    A_BY_VISIT = 'a:has-text("By Visit")'
    A_BY_INVOICE = 'a:has-text("By Invoice")'
    A_ELECTRONIC_BILLING = 'a:has-text("Electronic Billing")'
    A_E_SUBMISSION_BATCHES = 'a:has-text("E-Submission Batches")'
    A_ACTION = 'a:has-text("Action")'
    A_ACTION1 = 'a:has-text("Action")'
    A_OPERATION_WORKLIST = 'a:has-text("Operation Worklist")'
    A_IN_SERVICE = 'a:has-text("In Service")'
    A_NEW = 'a:has-text("New")'
    A_SEARCH = 'a:has-text("Search")'
    A_OVERTIME_DASHBOARD = 'a:has-text("Overtime Dashboard")'
    A_SEARCH_CAREGIVER_NEW = 'a:has-text("Search Caregiver (New)")'
    A_SEARCH_CAREGIVER_NEW_Under_SEARCH = "(//a[text()='Search Caregiver'])[2]"
    A_GENERAL_CAREGIVER_AVAILABILITY = 'a:has-text("General Caregiver Availability")'
    A_SEARCH_CAREGIVER_COMMUNICATION = 'a:has-text("Search Caregiver")'
    A_FILL_A_SHIFT = 'a:has-text("Fill a Shift")'
    A_TRAVEL_TIME = 'a:has-text("Travel Time")'
    A_REFERENCE_TABLE_MANAGEMENT = 'a:has-text("Reference Table Management")'
    A_VISIT = 'a:has-text("Visit")'
    A_QUICK_VISIT_ENTRY = 'a:has-text("Quick Visit Entry")'
    A_APPOINTMENT = 'a:has-text("Appointments")'
    A_PAYROLLL_SETUP = 'a:has-text("Payroll Setup")'
    A_PREBILLING = 'a:has-text("Prebilling")'
    A_VISIT_SEARCH = 'a:has-text("Visit Search")'
    A_REFERRAL_PATIENT_MANAGEMENT = 'a:has-text("Referral Patient Management")'
    A_SALES_STAFF = 'a:has-text("Sales Staff")'
    A_ATTRIBUTE_SETUP = 'a:has-text("Attributes Setup")'
    A_NEW_SALES_STAFF = 'a:has-text("New Sales Staff")'
    A_SEARCH_SALES_STAFF = 'a:has-text("Search Sales Staff")'
    A_SEARCH_REFERRAL_PATIENT = 'a:has-text("Search Referral Patient")'
    A_REFERRAL_PATIENT_SOURCE = 'a:has-text("Referral Patient Sources")'
    A_NEW_REFERRAL_PATIENT_SOURCE = 'a:has-text("New Referral Patient Source")'
    A_SEARCH_REFERRAL_PATIENT_SOURCE = 'a:has-text("Search Referral Patient Source")'
    A_REFERRAL_PATIENT_ELIGIBILITY_CHECK = 'a:has-text("Referral Patient Eligibility Check")'
    A_EDIT_SERVICE = 'a:has-text("Edit Services")'
    A_PLACEMENT = 'a:has-text("placement-label")'
    A_PENDING_PLACEMENT_TAB = 'a:has-text("pending-label")'
    A_PENDING_PLACEMENT_QUEUE = 'a:has-text("Pending Placement Queue (Agency")'
    A_STAFFED = 'a:has-text("Staffed")'
    A_STAFFED_PAGINATION = "//div[@id='tbVendorPendingStaffed_paginate']//ul[contains(@class,'pagination')]/li[not(contains(@class,'previous')) and not(contains(@class,'next'))]"
    A_STAFFED_CURRENT_PAGE = "//div[@id='tbVendorPendingStaffed_paginate']//li[@class='paginate_button current']"
    A_STAFFED_BTN_PAGE_NEXT = 'tbVendorPendingStaffed_next'
    A_STAFFED_BTN_PAGE_PREV = 'tbVendorPendingStaffed_previous'
    A_ACCEPTED_WITH_TEMP_CAREGIVER = 'a:has-text("Accepted with Temp Caregiver")'
    ACCEPTED_WITH_TEMP_CG_PAGINATION = "//div[@id='tbVendorPendingStaffedCaregiverObj_paginate']//ul[contains(@class,'pagination')]/li[not(contains(@class,'previous')) and not(contains(@class,'next'))]"
    PENDING_PLACEMENT_PAGINATION = "//div[@id='tbVendorPendingPlacement_paginate']//ul[contains(@class,'pagination')]/li[not(contains(@class,'previous')) and not(contains(@class,'next'))]"
    PENDING_PLACEMENT_CURRENT_PAGE = "//div[@id='tbVendorPendingPlacement_paginate']//li[@class='paginate_button current']"
    PENDING_PLACEMENT_BTN_PAGE_NEXT = 'tbVendorPendingPlacement_next'
    PENDING_PLACEMENT_BTN_PAGE_PREV = 'tbVendorPendingPlacement_previous'
    ADMISSION_ID_HEADER = "//table[@id='tbVendorPendingPlacement']//th[contains(text(),'Admission ID')]"
    ADMISSION_ID_COLUMN = "//table[@id='tbVendorPendingPlacement']//tbody/tr/td[2]/a"
    ACCEPTED_TEMP_CG_BTN_PAGE_NEXT = 'tbVendorPendingStaffedCaregiverObj_next'
    ACCEPTED_TEMP_CG_BTN_PAGE_PREV = 'tbVendorPendingStaffedCaregiverObj_previous'
    ACCEPTED_TEMP_CG_CURRENT_PAGE = "//div[@id='tbVendorPendingStaffedCaregiverObj_paginate']//li[@class='paginate_button current']"
    A_ACCEPTED_WITH_NO_MASTERWEEK = 'a:has-text("Accepted with No Master Week")'
    NEXT_BTN_ACCEPTED_NO_MASTERWEEK = 'tbVendorPendingAcceptedNoMasterweek_next'
    PREV_BTN_ACCEPTED_NO_MASTERWEEK = 'tbVendorPendingAcceptedNoMasterweek_previous'
    ACCEPTED_NO_MASTERWEEK_CURRENT_PAGE = "//div[@id='tbVendorPendingAcceptedNoMasterweek_paginate']//li[@class='paginate_button current']"
    ACCEPTED_NO_MASTERWEEK_PAGINATION = "//div[@id='tbVendorPendingAcceptedNoMasterweek_paginate']//ul[contains(@class,'pagination')]/li[not(contains(@class,'previous')) and not(contains(@class,'next'))]"
    BTN_CLOSE_BENEFICIARY_INFO_POPUP = 'uxbtnClose'
    A_CONFIRM_VISIT = 'a:has-text("Confirm Visits")'
    A_COLLECTION = 'a:has-text("Collection")'
    A_PTO_APPROVAL = 'a:has-text("PTO Approval")'
    A_BROADCAST_DASHBOARD = 'a:has-text("Broadcast Dashboard")'
    A_CONTRACT_COMMUNICATION = 'a:has-text("Contract Communications")'
    A_CARE_INSIDES_ALERT_DASHBOARD = 'a:has-text("Care Insights Alert Dashboard")'
    A_CONFIRM_TIMESHEET = 'a:has-text("Confirm Timesheet")'
    A_CAREGIVER_AWAKE_CONFIRMATION_DASHBOARD = 'a:has-text("Caregiver Awake Confirmation Dashboard")'
    A_PHYSICIAN_SETUP = 'a:has-text("Physician Setup")'
    A_NEW_PHYSICIAN = 'a:has-text("New Physician")'
    A_SEARCH_PHYSICIAN = 'a:has-text("Physician Search")'
    A_TRAINING_SCHOOL_SETUP = 'a:has-text("Training School Setup")'
    A_CARE_INSIGHT = 'a:has-text("Care Insights")'
    A_DATA_INSIGHTS = 'a:has-text("Data Insights")'
    A_BILLING_REVIEW = 'a:has-text("Billing Review")'
    A_PROFILE = 'a:has-text("User Profile Menu")'
    A_SUPPORT_CENTRE = 'a:has-text("Support Centre")'
    A_CALL_DASHBOARD = 'a:has-text("Call Dashboard")'
    A_CAREGIVER_COMMUNICATION_HISTORY = 'a:has-text("Caregiver Communications History")'
    Tab_received = 'page1_ah2'
    Receiver_Text = "//table[@id='page2_ContentPlaceHolder1_gvReceivedMessages']//tr[2]//td[6]"
    Receiver_Text3 = '//*[@id="showrecvmsgboxclick"]/div/div[1]/div[1]/h2'
    A_CHANGE_PASSWORD_ADMIN = '//*[@id="ulMenu"]/li[9]/ul/li[6]/a'
    A_EDI_TOOL = 'a:has-text("EDI Tool")'
    BUTTON_SEARCH_EDI = '//input[@value="Search"]'
    BUTTON_RESET_EDI = '//input[@value="Reset"]'
    A_OPERATION_WORKLIST_ADMIN = 'a:has-text("Ops Worklist Setup")'
    A_DUTY_LIST_SETUP = 'a:has-text("Duty List Setup")'
    A_COORDINATOR_SETUP = 'a:has-text("Coordinator Setup")'
    A_NEW_COORDINATOR = '//*[@id="ulMenu"]//a[normalize-space()="New Coordinator"]'
    A_SEARCH_COORDINATOR = '//*[@id="ulMenu"]//a[normalize-space()="New Coordinator"]'
    A_FORM = 'a:has-text("Forms")'
    A_IMPORT_FILES = 'a:has-text("Import Files")'
    A_USER_MANAGEMENT = 'a:has-text("User Management")'
    A_CHANGE_PASSWORD = 'a:has-text("Change Password")'
    A_USER_SEARCH = 'a:has-text("User Search")'
    A_Edit_Roles = 'a:has-text("Edit Roles")'
    D_ROLE_DROPDOWN = 'ddlSection'
    A_ADMIN_SEARCH_USER = '//*[@id="ctl00_ContentPlaceHolder1_uxbtnSearch"]'
    A_AGENCY_PROFILE = 'a:has-text("Agency Profile")'
    A_Service_Portal_Management = 'a:has-text("Services Portal Management")'
    A_SEARCH_BUTTON_BATCH = '//*[@id="btnSearch"]'
    A_BATCH_NUMBER = '//*[@id="tblGridPayrollBatch"]/tbody/tr[5]/td[1]/a'
    A_CAREGIVER_CODE = '//*[@id="ctl00_ContentPlaceHolder1_uxTxtAideCode"]'
    A_NEW_USER = 'a:has-text("New User")'
    A_REFERRAL_LINK = 'a:has-text("Referral Patient Management")'
    A_NEW_REFERRAL_PATIENT = 'a:has-text("New Referral Patient")'
    A_Service_Portal_User_Management = 'a:has-text("Services Portal User Management")'
    A_Announcements = 'a:has-text("Announcements")'
    A_SEARCH_BY_CAREGIVER = 'a:has-text("Search By Caregiver")'
    A_INPUT_OLD_PASSWORD_ADMIN = '//*[@id="ctl00_ContentPlaceHolder1_uxtxtOldPassword"]'
    A_INPUT_NEW_PASSWORD_ADMIN = '//*[@id="ctl00_ContentPlaceHolder1_uxtxtPassword"]'
    A_CONFIRM_PASSWORD_ADMIN = '//*[@id="ctl00_ContentPlaceHolder1_uxtxtConfirmPassword"]'
    A_BUTTON_SAVE_PASSWORD = '//*[@id="ctl00_ContentPlaceHolder1_uxbtnSave"]'
    A_DIRECT_MESSAGE = 'a:has-text("Direct Messages")'
    A_ADD_MESSAGE = 'page1_ContentPlaceHolder1_lnkNewMessage'
    A_ADD_MESSAGE2 = 'page2_ContentPlaceHolder1_lnkNewMessage'
    A_INTERNAL_MESSAGE = 'a:has-text("Internal Message")'
    A_RECEIVED = 'a:has-text("Received")'
    A_TASK = 'a:has-text("Tasks")'
    A_ADD_TASK = 'a:has-text("Add Task")'
    A_BULK_ACTION = 'a:has-text("Bulk Action")'
    A_Mobile_USER_MANAGEMENT = 'a:has-text("Mobile User Management")'
    A_Mobile_USER_SEARCH = '//*[@id="ctl00_ContentPlaceHolder1_uxbtnSearch"]'
    BUTTON_SEARCH = '#page2_ContentPlaceHolder1_btnSearchReceived'
    BUTTON_SEARCH_TASK = 'page2_ContentPlaceHolder1_btnSearchSent'
    BUTTON_SAVE_AS_READ = '//*[@id="btnRead" or normalize-space()="Mark as Read and Close"]'
    IFRAME_MESSAGE = 'ctl00_ContentPlaceHolder1_iframesentmessages'
    IFRAME_TO_DO = 'ctl00_ContentPlaceHolder1_iframesentodo'
    IFRAME_EVENT = 'ctl00_ContentPlaceHolder1_iframeevent'
    IFRAME_EDI_TOOL = 'ctl00_ContentPlaceHolder1_frameEDITool'
    INPUT_FROM_DATE = 'page2_ContentPlaceHolder1_txtFromDateReceived'
    INPUT_TO_DATE = 'page2_ContentPlaceHolder1_txtToDateReceived'
    INPUT_FROM_DATE_SENT = 'page2_ContentPlaceHolder1_txtFromDateSent'
    INPUT_TO_DATE_SENT = 'page2_ContentPlaceHolder1_txtToDateSent'
    SPAN_COUNT = 'page2_ContentPlaceHolder1_lblSearchResult'
    INPUT_PAYROLL_DATE = '//*[@id="ctl00_ContentPlaceHolder1_uxDtPayroll"]'
    PAYROLL_CAREGIVER_SEARCH = '//*[@id="ctl00_ContentPlaceHolder1_uxBtnSearch"]'
    A_REPORT = 'a:has-text("Report")'
    A_VISIT_COUNT = 'tdVisitCaseCountReskin'
    A_ReportingTool = 'a:has-text("Reporting Tool (2.0")'
    A_SYSTEM_NOTIFICATIONS_SEARCH = '//div[@id="sysNoti"]//*[@id="btnSearch"]'
    A_SELECT_PRIORITY2 = '//*[@id="ddlPrioritySent"]/option[2]'
    A_PRIORITY_SORTING = '//*[@id="gvRecNotification"]/tbody/tr[1]/th[3]/a'
    IFRAME_SYS_NOTI = 'ctl00_ContentPlaceHolder1_iframesysnoti'
    SYS_NOTI_CHECKBOX = '//*[@id="gvRecNotification_ctl04_chkDismiss"]'
    Eligibility_Batch_Review_Window = 'ctl00_ContentPlaceHolder1_ifrmEligibilityBatchDetails'
    Eligibility_Batch_Review_Search = '//input[@id="ctl00_ContentPlaceHolder1_btnSearch"]'
    A_FILE_PROCESSING = 'a:has-text("File Processing")'
    UPR_CONTRACT = 'UPR Contract'
    Select_Contract = 'ctl00_ContentPlaceHolder1_ddlContractType'
    Contract_Automation_UPR = '(//input[@data-text="Automation_UPR_Payer (India Only) (986)")'
    Contract_Choice_Dropdown = 'contractDdId_choice'
    CLAIM_GRIED_COUNT = '//table[@id="ctl00_ContentPlaceHolder1_gvFiles"]//tbody//tr'
    TAB_REMITTANCE = 'tpRemittances-label'
    REMITTANCE_SEARCH_BTN = 'ctl00_ContentPlaceHolder1_uxbtnSearchRemittances'
    a_hhaexchange = 'a:has-text("HHAeXchange")'
    url = 'https://www.hhaexchange.com/'
    a_customer_support = 'a:has-text("Support Center")'
    h1_heading = 'HHAeXchangeProviderKnowledgeBase'
    BUTTON_CLOSE_PENDO = '//*[contains(@id, "pendo-close-guide")]'
    Caregiver_Action = 'a:has-text("Action")'
    Pagination_Pending_Placement_Previous = 'tbVendorPendingPlacement_previous'
    Pagination_Pending_Placement_Next = 'tbVendorPendingPlacement_next'
    Pagination_Pending_Placement_Current = '//li[@id="tbVendorPendingStaffedCaregiverObj_previous"]/following-sibling::li[@class="paginate_button current"]'
    Pagination_Pending_Placement_Page_2 = '//li[@id="tbVendorPendingStaffedCaregiverObj_previous"]/following-sibling::li[@class="paginate_button" and text()="2"]'
    BTN_CONTINUE = '//form[@id="confirm"]//input[@value="Continue"]'
    OLD_ENT_LOGOUT = 'ctl00_LoginStatus1'
    TABLE_ALL_ROWS = '//table[contains(@class, "hhax-table")]//tbody/tr[td]'
    Main_Menu = 'button.menu-icon.bottom'
